### ISSUE TITLE
failed compositor init request. (0x80d40009 0x600000 0x10000000 0x0 0)

### ISSUE THREAD

**Issue by gen04177** [ps5-payload-dev/sdk#1]
[cube3d.zip](https://github.com/user-attachments/files/16073832/cube3d.zip)

**Comment by gen04177** [comment]
Give me OK to delete the files...thx...

**Comment by john-tornblom** [comment]
Please explain what your issue, attaching arbitrary files is not helpful

**Comment by gen04177** [comment]
In the .zip file there is a log file with the explanation

**Comment by gen04177** [comment]
I'm trying to create a 3D cube using video acceleration and it returns the error contained in the log.txt file that is compressed in the zip file.

**Comment by gen04177** [comment]
I will delete the file, if you need testing please let me know. I would really like the code to work. Thanks for your patience!

**Comment by john-tornblom** [comment]
Yeez, why do you put the log in a zip file, just put it in the issue report!
The problem you are addressing is interesting, but out of scope of SDK, clsoing..
